DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS FUNDING_INFO;
DROP TABLE IF EXISTS ITEM_OPTION;


CREATE TABLE USERS(
    ID LONG PRIMARY KEY AUTO_INCREMENT,
    USER_ID VARCHAR(20),
    PASSWORD VARCHAR(20),
    USER_NAME VARCHAR(20),
    EMAIL VARCHAR(30),
    PHONE VARCHAR(11),
    SI VARCHAR(10),
    GU VARCHAR(10),
    DONG VARCHAR(10),
    ADDRESS VARCHAR(20),
    USER_ROLE INT
);

CREATE TABLE FUNDING_INFO(
      ID LONG PRIMARY KEY AUTO_INCREMENT,
      FUNDING_TITLE VARCHAR(20),
      FUNDING_DESC VARCHAR(200),
      START_DT DATE,
      TARGET_DT DATE,
      TARGET_PRICE NUMERIC,
      FUNDING_STATUS INT
);

CREATE TABLE ITEM_OPTION(
     ID LONG PRIMARY KEY AUTO_INCREMENT,
     FUNDING_ID LONG,
     ITEM_NAME VARCHAR(20),
     ITEM_PRICE NUMERIC ,
     QUANTITY INT
);