DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS(
    ID LONG PRIMARY KEY,
    USER_ID VARCHAR(20),
    PASSWORD VARCHAR(20),
    USER_NAME VARCHAR(20),
    EMAIL VARCHAR(30),
    PHONE VARCHAR(11),
    SI VARCHAR(10),
    GU VARCHAR(10),
    DONG VARCHAR(10),
    ADDRESS VARCHAR(20),
    USER_ROLE INT
);